// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACno-l0pyuAmuxMynP4v3NFZem7euk98w',
    appId: '1:573210495277:web:42cb809329375b7b02aba4',
    messagingSenderId: '573210495277',
    projectId: 'appp-609fe',
    authDomain: 'appp-609fe.firebaseapp.com',
    storageBucket: 'appp-609fe.firebasestorage.app',
    measurementId: 'G-XS0X1RD5EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRX2ZzAFjdocLbhYkdYKkYJuJYImqdwGQ',
    appId: '1:573210495277:android:25a5f72cdd53bb9f02aba4',
    messagingSenderId: '573210495277',
    projectId: 'appp-609fe',
    storageBucket: 'appp-609fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmjj8Qs1HDH9SXMHe-0gz0d4A8GP3CfAQ',
    appId: '1:573210495277:ios:815aa7c2d170149102aba4',
    messagingSenderId: '573210495277',
    projectId: 'appp-609fe',
    storageBucket: 'appp-609fe.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmjj8Qs1HDH9SXMHe-0gz0d4A8GP3CfAQ',
    appId: '1:573210495277:ios:815aa7c2d170149102aba4',
    messagingSenderId: '573210495277',
    projectId: 'appp-609fe',
    storageBucket: 'appp-609fe.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACno-l0pyuAmuxMynP4v3NFZem7euk98w',
    appId: '1:573210495277:web:9f46e6d0051ec75302aba4',
    messagingSenderId: '573210495277',
    projectId: 'appp-609fe',
    authDomain: 'appp-609fe.firebaseapp.com',
    storageBucket: 'appp-609fe.firebasestorage.app',
    measurementId: 'G-PZHH5GX2XK',
  );

}